kind: PersistentVolume
apiVersion: v1
metadata:
  name: znc-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/znc-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znc-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

