apiVersion: v1
kind: Service
metadata:
  name: znc
  labels:
    app: znc
spec:
  type: NodePort
  ports:
  - port: 6697
    name: irc
  - port: 8443
    name: ircweb
  selector:
    app: znc
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: znc
spec:
  selector:
    matchLabels:
      app: znc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: znc
    spec:
      containers:
      - image: znc:latest
        name: znc
        ports:
        - containerPort: 6697
        - containerPort: 8443
          name: znc
        volumeMounts:
        - name: znc-persistent-storage
          mountPath: /znc-data
      volumes:
      - name: znc-persistent-storage
        persistentVolumeClaim:
          claimName: znc-pv-claim
